version: '3'
services:
  web:
    image: pyredis
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks: 
      - iredis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    networks: 
      - iredis
    volumes:
      - vredis:/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M

networks:
  iredis:

volumes:
  vredis:

# docker swarm init
# docker stack deploy --compose-file docker-compose.yml pyredisCluster
# docker stack rm pyredisCluster
# docker swarm leave --force
